created ExchangeRateService
mate-academy/bank-service-springboot-reference-project pull request #4
Opened 2021-02-05 10:13 UTC by KseniiaMakarova

2021-02-05 11:51 UTC, Sofasmile commented on src/main/java/com/academy/mate/bankservice/exchange/NbuExchangeRateService.java
> +    private static final String BASE_URL = "https://bank.gov.ua/NBUStatService/v1/statdirectory/exchangenew";
maybe better move url to application.properties?

2021-02-05 11:51 UTC, Sofasmile commented on src/main/java/com/academy/mate/bankservice/exchange/NbuExchangeRateService.java
> +    private final ObjectMapper objectMapper;
if I remember we can autowiere ObjectMapper

2021-02-05 11:51 UTC, Sofasmile commented on src/main/java/com/academy/mate/bankservice/exchange/NbuExchangeRateService.java
> +    @SneakyThrows
we ask student's don't use SneakyThrows annotation

2021-02-05 13:20 UTC, KseniiaMakarova commented on src/main/java/com/academy/mate/bankservice/exchange/NbuExchangeRateService.java
> +    @SneakyThrows
sure

2021-02-05 13:36 UTC, Sofasmile approved these changes

2021-02-05 15:45 UTC, boroda4436 requested changes

2021-02-05 15:45 UTC, boroda4436 commented on src/main/java/com/academy/mate/bankservice/exchange/ExchangeRateService.java
> +    double getUahRate(Currency currency, LocalDate date);
```suggestion
    double getRate(Currency currencyFrom, Currency currencyTo, LocalDate date);
```

2021-02-05 16:06 UTC, boroda4436 commented on src/main/java/com/academy/mate/bankservice/exchange/ExchangeRateService.java
> +    double getUahRate(Currency currency, LocalDate date);
ох уж це АПІ... окей

2021-02-05 16:35 UTC, boroda4436 commented on src/main/java/com/academy/mate/bankservice/exchange/NbuExchangeRateService.java
> +        if (to != Currency.UAH) {
Це ж тестовий проект? Ми можемо заюзати інше API?

2021-02-05 16:36 UTC, boroda4436 commented on src/main/java/com/academy/mate/bankservice/exchange/NbuExchangeRateService.java
> +        if (to != Currency.UAH) {
студенти не додумаються і це потенційний блокер для них

2021-02-05 16:36 UTC, KseniiaMakarova commented on src/main/java/com/academy/mate/bankservice/exchange/NbuExchangeRateService.java
> +        if (to != Currency.UAH) {
ок, тогда нужно будет поискать другое)

2021-02-16 07:28 UTC, boroda4436 approved these changes

2021-02-16 08:57 UTC, Sofasmile approved these changes

2021-02-16 09:21 UTC, merged